# Generated by Django 4.0.3 on 2022-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='purpose',
            field=models.IntegerField(choices=[(0, 'Blogger'), (1, 'Creator'), (2, 'Subscriber'), (3, 'The_others')], db_column='purpose', default=3, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='username', max_length=150, unique=True, verbose_name='user_id'),
        ),
    ]
