# Generated by Django 4.0.3 on 2022-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_purpose_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='username', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
